# ==============================================================================
# RDSK Monitoring Server CMake File
# ==============================================================================

# include subdirectories -------------------------------------------------------

INSTALL(DIRECTORY
            skel
        DESTINATION
            etc/
        )



